from collections.abc import Sequence
from typing import Protocol

from github_orchestrator.domain import Pr


class ReportCommands(Protocol):
    def skip(self, pr: Pr, key: str, *, reason: str) -> str: ...

    def reply(self, pr: Pr, key: str, *, body: str) -> str: ...

    def ticket(self, pr: Pr, key: str, *, project: str, title: str, body: str,
               reply: str) -> str: ...

    def plan(self, pr: Pr, key: str, steps: Sequence[tuple[str, str]]) -> str: ...

    def step(self, pr: Pr, key: str, *, done: str) -> str: ...

    def ready(self, pr: Pr, key: str, *, sha: str, tests_note: str, note: str, summary: str,
              confidence: str, confidence_note: str) -> str: ...

    def fail(self, pr: Pr, key: str, *, reason: str) -> str: ...

    def filed(self, pr: Pr, key: str, *, ticket: str, url: str) -> str: ...

    def draft(self, pr: Pr, *, path: str, line: str, start_line: str, body_file: str) -> str: ...
